export const allServices = [
  {
    id: 1,
    title: "AI-Powered Business Solutions",
    image: require("../assets/images/services/ai.webp"),
    desc: "Transform your business operations with our custom AI solutions that automate processes, generate insights, and drive intelligent decision-making.",
    link: "/ai-services",
    category: "ai",
    problem: "Manual processes consuming valuable time and resources",
    useCase: "Automated document processing reducing manual work by 85%",
    industries: ["Finance", "Healthcare", "Manufacturing", "Retail"]
  },
  // {
  //   id: 2,
  //   title: "Custom AI Agents",
  //   image: require("../assets/images/services/aicallingagency.webp"),
  //   desc: "Deploy intelligent AI agents that handle specific business functions autonomously, from customer service to internal workflows and operations.",
  //   link: "/ai-services",
  //   category: "ai",
  //   problem: "Inefficient customer service and support operations",
  //   useCase: "AI agent handling 70% of customer inquiries without human intervention",
  //   industries: ["E-commerce", "SaaS", "Banking", "Insurance"]
  // },
  {
    id: 3,
    title: "AR/VR Development",
    image: require("../assets/images/services/arvr.webp"),
    desc: "Create immersive augmented and virtual reality experiences that transform how users interact with your products, services, and training materials.",
    link: "/ar-vr-development",
    category: "arvr",
    problem: "Ineffective traditional training and visualization methods",
    useCase: "VR training reducing learning time by 60% while improving retention",
    industries: ["Education", "Real Estate", "Healthcare", "Retail"]
  },
  {
    id: 4,
    title: "Smart Bots & Workflow Automation",
    image: require("../assets/images/services/chatbot.webp"),
    desc: "Streamline operations with intelligent bots that automate repetitive tasks, enhance communication, and optimize internal and external workflows.",
    category: "ai",
    problem: "Time-consuming repetitive tasks and inefficient workflows",
    useCase: "Workflow automation reducing processing time from days to minutes",
    industries: ["HR", "Operations", "Customer Service", "Administration"]
  },
  {
    id: 5,
    title: "Machine Learning Solutions",
    image: require("../assets/images/services/ml.webp"),
    desc: "Leverage the power of data with custom machine learning models that predict outcomes, identify patterns, and continuously improve with new information.",
    category: "ai",
    problem: "Inability to predict customer behavior and business trends",
    useCase: "Predictive analytics increasing sales conversion rates by 35%",
    industries: ["Retail", "Finance", "Healthcare", "Marketing"]
  },
  // {
  //   id: 6,
  //   title: "Natural Language Processing",
  //   image: require("../assets/images/services/nlp.webp"),
  //   desc: "Enable your systems to understand, interpret, and generate human language with our advanced NLP solutions for smarter interactions.",
  //   category: "ai",
  //   problem: "Difficulty processing and analyzing unstructured text data",
  //   useCase: "Sentiment analysis providing real-time customer feedback insights",
  //   industries: ["Customer Service", "Content Management", "Social Media", "Market Research"]
  // },
  // {
  //   id: 7,
  //   title: "Immersive AR Product Visualization",
  //   image: require("../assets/images/services/arvr.webp"),
  //   desc: "Showcase your products in augmented reality, allowing customers to visualize items in their own space before purchasing.",
  //   link: "/ar-vr-development",
  //   category: "arvr",
  //   problem: "High product return rates due to expectation mismatch",
  //   useCase: "AR product visualization reducing returns by 40%",
  //   industries: ["Furniture", "Fashion", "Home Decor", "Electronics"]
  // },
  {
    id: 8,
    title: "VR Training & Simulation",
    image: require("../assets/images/services/gaming.webp"),
    desc: "Create realistic virtual training environments that improve skill acquisition, retention, and safety for complex or high-risk procedures.",
    link: "/ar-vr-development",
    category: "arvr",
    problem: "High-risk or expensive traditional training methods",
    useCase: "VR simulation reducing training costs by 50% while improving safety",
    industries: ["Manufacturing", "Healthcare", "Aviation", "Military"]
  },
  // {
  //   id: 9,
  //   title: "Data Analytics & Business Intelligence",
  //   image: require("../assets/images/services/data-analytics.webp"),
  //   desc: "Transform raw data into actionable insights with our comprehensive analytics solutions that drive strategic decision-making and business growth.",
  //   category: "ai",
  //   problem: "Overwhelming data without actionable insights",
  //   useCase: "Interactive dashboards enabling data-driven decisions that increased efficiency by 25%",
  //   industries: ["Finance", "Retail", "Healthcare", "Manufacturing"]
  // },
  // {
  //   id: 10,
  //   title: "Computer Vision Systems",
  //   image: require("../assets/images/services/ai.webp"),
  //   desc: "Implement AI-powered visual recognition systems for object detection, facial recognition, quality control, and automated monitoring.",
  //   category: "ai",
  //   problem: "Manual visual inspection processes prone to human error",
  //   useCase: "Automated quality control reducing defects by 90%",
  //   industries: ["Manufacturing", "Security", "Retail", "Healthcare"]
  // },
  {
    id: 11,
    title: "Mobile App Development",
    image: require("../assets/images/services/app-development.webp"),
    desc: "Create powerful, user-friendly mobile applications enhanced with AI capabilities for both iOS and Android platforms.",
    link: "/app-development",
    category: "development",
    problem: "Lack of mobile presence and engagement",
    useCase: "AI-enhanced mobile app increasing customer engagement by 40%",
    industries: ["Retail", "Finance", "Healthcare", "Entertainment"]
  },
  {
    id: 12,
    title: "Web Development (Full Stack)",
    image: require("../assets/images/services/web-development.webp"),
    desc: "Build modern, responsive websites and web applications with integrated AI features for enhanced user experiences.",
    link: "/web-development",
    category: "development",
    problem: "Outdated web presence with poor user experience",
    useCase: "AI-powered website increasing conversion rates by 30%",
    industries: ["E-commerce", "SaaS", "Media", "Professional Services"]
  },
  {
    id: 13,
    title: "Blockchain Development",
    image: require("../assets/images/services/blockchain.webp"),
    desc: "Implement secure, transparent blockchain solutions for digital transactions, smart contracts, and decentralized applications.",
    category: "development",
    problem: "Trust and transparency issues in transactions and record-keeping",
    useCase: "Blockchain solution reducing fraud by 95% in supply chain",
    industries: ["Finance", "Supply Chain", "Healthcare", "Real Estate"]
  },
  {
    id: 14,
    title: "UI/UX Design",
    image: require("../assets/images/services/uiux.webp"),
    desc: "Create intuitive, engaging user interfaces and experiences that delight users while achieving your business objectives.",
    category: "development",
    problem: "Poor user engagement and high bounce rates",
    useCase: "Redesigned UX increasing user retention by 55%",
    industries: ["E-commerce", "SaaS", "Finance", "Healthcare"]
  },
];


// Web Development Services
export const webDevelopmentServices = [
  {
    id: 1,
    title: "Custom Website Design",
    image: require("../assets/images/landing page/Custom Website Design.webp"),
    description:
      "We design visually stunning, user-friendly websites that perfectly reflect your brand identity and business goals. Our responsive designs adapt seamlessly to all screen sizes, ensuring an optimal experience across desktops, tablets, and mobile devices. We combine aesthetic appeal with intuitive navigation to maximize user engagement and conversion rates.",
  },
  {
    id: 2,
    title: "E-commerce Solutions",
    image: require("../assets/images/landing page/E-commerce Solutions.webp"),
    description:
      "We build secure, high-performing e-commerce platforms with seamless payment integration and inventory management systems. Our solutions include customized product catalogs, secure checkout processes, and comprehensive analytics dashboards that help you track sales, customer behavior, and marketing effectiveness to boost your online revenue and enhance the overall shopping experience.",
  },
  {
    id: 3,
    title: "Content Management Systems",
    image: require("../assets/images/landing page/Content Management Systems.webp"),
    description:
      "Our CMS solutions empower you to easily manage and update your website content without technical expertise. We implement and customize platforms like WordPress, Joomla, and Drupal with intuitive admin interfaces, content scheduling capabilities, and SEO optimization tools. Our systems are designed for scalability, allowing your website to grow alongside your business.",
  },
  {
    id: 4,
    title: "API Integration",
    image: require("../assets/images/landing page/API Integration.webp"),
    description:
      "We seamlessly connect your website to essential third-party services through robust API integrations. From payment gateways and CRM systems to social media platforms and marketing automation tools, our integration expertise ensures your website functions as a central hub for all your business operations, automating workflows and enhancing data consistency across all your systems.",
  },
  {
    id: 5,
    title: "Website Maintenance & Support",
    image: require("../assets/images/landing page/Website Maintenance & Support.webp"),
    description:
      "We provide comprehensive website maintenance services including regular updates, security patches, performance optimization, and content updates. Our proactive monitoring systems detect and address potential issues before they impact your users, ensuring your website remains secure, fast, and reliable. We offer flexible support packages with dedicated response times to meet your specific business needs.",
  },
];

// App Development Services
export const appDevelopmentServices = [
  {
    id: 1,
    title: "iOS App Development",
    image: require("../assets/images/landing page/iOS App Development.webp"),
    description:
      "We create high-performance iOS apps optimized for iPhones, iPads, and Apple Watch, leveraging Swift and SwiftUI to deliver exceptional user experiences. Our iOS applications feature seamless Apple ecosystem integration, utilize device-specific capabilities, and adhere to Apple's strict design guidelines while incorporating the latest iOS features to ensure your app stands out in the App Store.",
  },
  {
    id: 2,
    title: "Android App Development",
    image: require("../assets/images/landing page/Android App Development.webp"),
    description:
      "Our Android apps are engineered for smooth performance, scalability, and user engagement across the diverse Android device ecosystem. Using Kotlin and Java, we develop applications that adapt to different screen sizes and hardware specifications while maintaining consistent functionality. We implement Material Design principles and optimize for battery efficiency to deliver exceptional Android experiences.",
  },
  {
    id: 3,
    title: "Cross-Platform App Development",
    image: require("../assets/images/landing page/Cross-Platform App Development.webp"),
    description:
      "Using React Native and Flutter frameworks, we develop cross-platform applications that provide native-like experiences on both iOS and Android from a single codebase. This approach significantly reduces development time and maintenance costs while ensuring consistent functionality and design across platforms. Our cross-platform solutions deliver excellent performance with near-native user experiences.",
  },
  {
    id: 4,
    title: "UI/UX Design for Apps",
    image: require("../assets/images/landing page/UIUX Design for Apps.webp"),
    description:
      "We craft intuitive, visually appealing UI/UX designs that enhance user engagement and ensure seamless app navigation. Our design process includes user research, wireframing, prototyping, and usability testing to create interfaces that are both aesthetically pleasing and functionally efficient. We focus on creating memorable brand experiences through thoughtful animations, micro-interactions, and accessibility features.",
  },
  {
    id: 5,
    title: "App Testing & Deployment",
    image: require("../assets/images/landing page/App Testing & Deployment.webp"),
    description:
      "We rigorously test applications across multiple dimensions including functionality, performance, usability, security, and compatibility with various devices. Our comprehensive testing methodology identifies and resolves issues before they reach users, ensuring a smooth launch on the App Store and Google Play. We also provide continuous integration, delivery pipelines, and post-launch analytics to monitor app performance and user engagement.",
  },
];

// Service details page content
export const serviceDetailsList = [
  {
    id: 1,
    title: "AI-Powered Calling Agency",
    shortDescription: "Voice and video calling systems with human-like interaction",
    heroImage: "/images/services/ai-calling.jpg",
    overview:
      "We design sophisticated voice and video calling systems that sound natural, speak multiple languages, and help businesses automate calls without losing the human touch. Our AI calling solutions enable seamless customer interactions, appointment scheduling, and follow-ups at scale.",
    features: [
      "Natural-sounding voice synthesis",
      "Multi-language support",
      "Contextual conversation handling",
      "Call scheduling and automation",
      "Integration with CRM systems",
      "Call analytics and insights",
      "Custom voice development",
      "Sentiment analysis during calls",
    ],
    technologies: [
      {
        name: "Voice AI",
        items: ["Google WaveNet", "Amazon Polly", "Microsoft Neural Voices", "OpenAI TTS"],
      },
      {
        name: "Conversation AI",
        items: ["GPT-4", "Claude", "Dialogflow", "Rasa"],
      },
      {
        name: "Integration",
        items: ["Twilio", "Vonage", "Amazon Connect", "Genesys"],
      },
      {
        name: "Analytics",
        items: ["Call sentiment analysis", "Conversation intelligence", "Performance metrics"],
      },
    ],
    process: [
      {
        step: 1,
        title: "Use Case Definition",
        description: "Identify calling scenarios and requirements",
      },
      {
        step: 2,
        title: "Voice Selection",
        description: "Choose or create the right voice for your brand",
      },
      {
        step: 3,
        title: "Script Development",
        description: "Create conversation flows and responses",
      },
      {
        step: 4,
        title: "AI Training",
        description: "Train the system on your specific domain",
      },
      {
        step: 5,
        title: "Integration",
        description: "Connect with your existing systems",
      },
      {
        step: 6,
        title: "Testing & Refinement",
        description: "Optimize for natural conversations",
      },
    ],
    benefits: [
      "Scale customer outreach without increasing staff",
      "Consistent brand voice across all calls",
      "24/7 availability for global operations",
      "Reduced operational costs",
      "Detailed analytics on customer interactions",
    ],
  },
  {
    id: 2,
    title: "AI-Powered Chatbot Development",
    shortDescription: "Intelligent conversational interfaces for customer engagement",
    heroImage: "/images/services/ai-chatbot.jpg",
    overview:
      "We build intelligent chatbots that truly understand human language, providing fast, helpful responses while making customer support more efficient, quicker, and available 24/7. Our chatbots learn from interactions to continuously improve their performance and accuracy.",
    features: [
      "Natural language understanding",
      "Context-aware conversations",
      "Multi-platform deployment",
      "Seamless human handoff",
      "Knowledge base integration",
      "Personalized user experiences",
      "Multi-language support",
      "Analytics and performance tracking",
    ],
    technologies: [
      { name: "AI Models", items: ["GPT-4", "Claude", "LLaMA", "PaLM"] },
      { name: "Platforms", items: ["Dialogflow", "Rasa", "Microsoft Bot Framework", "Custom solutions"] },
      { name: "Integration", items: ["Website widgets", "WhatsApp", "Slack", "Microsoft Teams", "Telegram"] },
      { name: "Backend", items: ["Node.js", "Python", "Vector databases", "Redis"] },
    ],
    process: [
      {
        step: 1,
        title: "Requirements Analysis",
        description: "Define chatbot goals and use cases",
      },
      {
        step: 2,
        title: "Conversation Design",
        description: "Create dialogue flows and personality",
      },
      {
        step: 3,
        title: "Knowledge Base Creation",
        description: "Develop content for responses",
      },
      {
        step: 4,
        title: "Development",
        description: "Build and train the chatbot",
      },
      {
        step: 5,
        title: "Integration",
        description: "Deploy across chosen platforms",
      },
      {
        step: 6,
        title: "Continuous Improvement",
        description: "Analyze and refine based on user interactions",
      },
    ],
    benefits: [
      "24/7 customer support availability",
      "Reduced response times",
      "Consistent answers to common questions",
      "Scalable customer service solution",
      "Valuable insights from customer interactions",
    ],
  },
  {
    id: 3,
    title: "Blockchain Development",
    shortDescription: "Secure, transparent distributed ledger solutions",
    heroImage: "/images/services/blockchain.jpg",
    overview:
      "From smart contracts to secure digital records, we help businesses build practical blockchain solutions that improve trust, transparency, and efficiency across industries. Our blockchain implementations solve real business problems while leveraging the security and immutability of distributed ledger technology.",
    features: [
      "Smart contract development",
      "Decentralized applications (dApps)",
      "Token creation and management",
      "Supply chain tracking",
      "Digital identity solutions",
      "NFT marketplaces",
      "DeFi platforms",
      "Enterprise blockchain solutions",
    ],
    technologies: [
      {
        name: "Platforms",
        items: ["Ethereum", "Polygon", "Solana", "Hyperledger Fabric", "Corda"],
      },
      { name: "Languages", items: ["Solidity", "Rust", "Go", "JavaScript"] },
      { name: "Tools", items: ["Truffle", "Hardhat", "Web3.js", "Ethers.js", "The Graph"] },
      { name: "Security", items: ["Smart contract auditing", "Penetration testing", "Formal verification"] },
    ],
    process: [
      { step: 1, title: "Use Case Analysis", description: "Identify blockchain-appropriate problems" },
      {
        step: 2,
        title: "Architecture Design",
        description: "Select platform and design system",
      },
      { step: 3, title: "Development", description: "Build smart contracts and applications" },
      { step: 4, title: "Security Audit", description: "Verify code security and reliability" },
      { step: 5, title: "Testing", description: "Validate functionality and performance" },
      {
        step: 6,
        title: "Deployment & Monitoring",
        description: "Launch and maintain the solution",
      },
    ],
    benefits: [
      "Enhanced security through cryptographic verification",
      "Increased transparency in business processes",
      "Reduced intermediaries and associated costs",
      "Immutable record-keeping",
      "Automated trust through smart contracts",
    ],
  },
  {
    id: 4,
    title: "Cloud Computing & Migration Services",
    shortDescription: "Seamless transition to scalable cloud infrastructure",
    heroImage: "/images/services/cloud-computing.jpg",
    overview:
      "We help businesses move to the cloud smoothly, reduce IT complexities, and scale with ease—whether starting fresh or upgrading from legacy systems. Our cloud solutions provide flexibility, security, and cost efficiency while ensuring minimal disruption to your operations.",
    features: [
      "Cloud migration strategy",
      "Infrastructure as Code (IaC)",
      "Serverless architecture",
      "Multi-cloud deployments",
      "Cloud security implementation",
      "Cost optimization",
      "DevOps automation",
      "Disaster recovery planning",
    ],
    technologies: [
      { name: "Platforms", items: ["AWS", "Microsoft Azure", "Google Cloud", "IBM Cloud"] },
      { name: "Infrastructure", items: ["Terraform", "CloudFormation", "Kubernetes", "Docker"] },
      { name: "DevOps", items: ["CI/CD pipelines", "Jenkins", "GitHub Actions", "GitLab CI"] },
      { name: "Monitoring", items: ["Prometheus", "Grafana", "New Relic", "Datadog"] },
    ],
    process: [
      { step: 1, title: "Assessment", description: "Evaluate current infrastructure and needs" },
      {
        step: 2,
        title: "Strategy",
        description: "Develop migration plan and architecture",
      },
      { step: 3, title: "Preparation", description: "Set up cloud environment and tools" },
      { step: 4, title: "Migration", description: "Move applications and data in phases" },
      { step: 5, title: "Optimization", description: "Fine-tune performance and costs" },
      {
        step: 6,
        title: "Management",
        description: "Provide ongoing support and monitoring",
      },
    ],
    benefits: [
      "Improved scalability to handle growth",
      "Reduced infrastructure maintenance costs",
      "Enhanced reliability and uptime",
      "Pay-as-you-go pricing model",
      "Faster deployment of new features",
    ],
  },
  {
    id: 5,
    title: "Data Analytics & Business Intelligence",
    shortDescription: "Transforming data into actionable business insights",
    heroImage: "/images/services/data-analytics.jpg",
    overview:
      "We help teams make sense of their data—turning numbers into insights, dashboards into decisions, and strategies into real, measurable results. Our data analytics solutions enable businesses to discover patterns, predict trends, and make data-driven decisions with confidence.",
    features: [
      "Data warehouse design",
      "ETL pipeline development",
      "Interactive dashboards",
      "Predictive analytics",
      "Real-time data processing",
      "KPI tracking and reporting",
      "Data visualization",
      "Custom analytics solutions",
    ],
    technologies: [
      { name: "Platforms", items: ["Tableau", "Power BI", "Looker", "Qlik"] },
      { name: "Data Processing", items: ["Apache Spark", "Hadoop", "Kafka", "Airflow"] },
      { name: "Languages", items: ["Python", "R", "SQL", "DAX"] },
      { name: "Cloud Analytics", items: ["Snowflake", "BigQuery", "Redshift", "Azure Synapse"] },
    ],
    process: [
      { step: 1, title: "Data Discovery", description: "Identify data sources and requirements" },
      {
        step: 2,
        title: "Data Preparation",
        description: "Clean, transform, and structure data",
      },
      { step: 3, title: "Data Modeling", description: "Create analytical data models" },
      { step: 4, title: "Analysis", description: "Apply statistical and analytical methods" },
      { step: 5, title: "Visualization", description: "Build intuitive dashboards and reports" },
      {
        step: 6,
        title: "Implementation",
        description: "Deploy and train teams on solutions",
      },
    ],
    benefits: [
      "Data-driven decision making",
      "Early identification of market trends",
      "Improved operational efficiency",
      "Enhanced customer understanding",
      "Competitive advantage through insights",
    ],
  },
  {
    id: 6,
    title: "Internet of Things (IoT) Development",
    shortDescription: "Connected device ecosystems for smart operations",
    heroImage: "/images/services/iot.jpg",
    overview:
      "We create smart, connected products that communicate with each other. From home automation to industrial IoT, we turn data from physical devices into intelligent actions that improve efficiency, provide insights, and enable new business models.",
    features: [
      "IoT device prototyping",
      "Sensor integration",
      "Edge computing solutions",
      "IoT platform development",
      "Real-time monitoring systems",
      "Predictive maintenance",
      "Smart home/office automation",
      "Industrial IoT implementations",
    ],
    technologies: [
      { name: "Hardware", items: ["Arduino", "Raspberry Pi", "ESP32", "Custom hardware"] },
      { name: "Connectivity", items: ["WiFi", "Bluetooth", "LoRaWAN", "5G", "MQTT"] },
      { name: "Platforms", items: ["AWS IoT", "Azure IoT", "Google Cloud IoT", "ThingsBoard"] },
      { name: "Analytics", items: ["Stream processing", "Time-series databases", "Machine learning"] },
    ],
    process: [
      { step: 1, title: "Concept Development", description: "Define IoT use case and requirements" },
      { step: 2, title: "Hardware Selection", description: "Choose appropriate devices and sensors" },
      { step: 3, title: "Architecture Design", description: "Plan connectivity and data flow" },
      { step: 4, title: "Development", description: "Build device firmware and backend systems" },
      { step: 5, title: "Testing", description: "Validate functionality and security" },
      { step: 6, title: "Deployment", description: "Roll out and monitor the IoT ecosystem" },
    ],
    benefits: [
      "Real-time operational visibility",
      "Automated processes and reduced manual intervention",
      "Predictive maintenance to prevent failures",
      "Data-driven insights for business optimization",
      "New revenue streams through connected products",
    ],
  },
  {
    id: 7,
    title: "Artificial Intelligence Development",
    shortDescription: "Custom AI solutions for business automation and intelligence",
    heroImage: "/images/services/ai.jpg",
    overview:
      "We develop AI tools tailored to your business—from automation to intelligent recommendations—so your systems work faster, learn smarter, and think ahead. Our AI solutions solve real business problems while adapting to changing conditions and improving over time.",
    features: [
      "Custom machine learning models",
      "Computer vision systems",
      "Natural language processing",
      "Predictive analytics",
      "Recommendation engines",
      "Anomaly detection",
      "Process automation",
      "AI strategy consulting",
    ],
    technologies: [
      { name: "Frameworks", items: ["TensorFlow", "PyTorch", "Scikit-learn", "Hugging Face"] },
      { name: "Cloud AI", items: ["AWS SageMaker", "Google Vertex AI", "Azure ML"] },
      { name: "Data Processing", items: ["Pandas", "Spark", "Dask", "Ray"] },
      { name: "Deployment", items: ["MLOps", "Model serving", "Edge AI", "TensorRT"] },
    ],
    process: [
      { step: 1, title: "Problem Definition", description: "Identify AI-appropriate challenges" },
      { step: 2, title: "Data Collection", description: "Gather and prepare training data" },
      { step: 3, title: "Model Development", description: "Build and train AI models" },
      { step: 4, title: "Evaluation", description: "Test performance against metrics" },
      { step: 5, title: "Deployment", description: "Integrate AI into production systems" },
      { step: 6, title: "Monitoring", description: "Track performance and retrain as needed" },
    ],
    benefits: [
      "Automation of repetitive tasks",
      "Enhanced decision-making capabilities",
      "Personalized customer experiences",
      "Predictive insights for planning",
      "Competitive advantage through innovation",
    ],
  },
  {
    id: 8,
    title: "Virtual Reality (VR) & Augmented Reality (AR)",
    shortDescription: "Immersive digital experiences that transform engagement",
    heroImage: "/images/services/vr-ar.jpg",
    overview:
      "We craft immersive VR/AR experiences that blend digital and real worlds—perfect for training, gaming, and storytelling that leaves a lasting impression. Our solutions create engaging, interactive environments that solve business problems and captivate audiences.",
    features: [
      "VR application development",
      "AR mobile applications",
      "Mixed reality experiences",
      "3D modeling and animation",
      "Interactive training simulations",
      "Virtual showrooms and tours",
      "AR product visualization",
      "Immersive storytelling",
    ],
    technologies: [
      { name: "Platforms", items: ["Unity", "Unreal Engine", "ARKit", "ARCore"] },
      { name: "Hardware", items: ["Oculus", "HTC Vive", "Microsoft HoloLens", "Mobile AR"] },
      { name: "3D", items: ["Blender", "Maya", "3ds Max", "WebXR"] },
      { name: "Interaction", items: ["Motion tracking", "Spatial mapping", "Gesture recognition"] },
    ],
    process: [
      { step: 1, title: "Concept Design", description: "Define experience goals and storyboarding" },
      { step: 2, title: "3D Asset Creation", description: "Develop models and environments" },
      { step: 3, title: "Interaction Design", description: "Create intuitive user interactions" },
      { step: 4, title: "Development", description: "Build the VR/AR application" },
      { step: 5, title: "Testing", description: "Validate user experience and performance" },
      { step: 6, title: "Deployment", description: "Launch on target platforms" },
    ],
    benefits: [
      "Enhanced training effectiveness and retention",
      "Reduced costs for physical prototyping",
      "Engaging marketing and sales experiences",
      "Remote collaboration capabilities",
      "Innovative customer experiences",
    ],
  },
  {
    id: 9,
    title: "UI and UX Design",
    shortDescription: "User-centered design that enhances digital experiences",
    heroImage: "/images/services/ui-ux.jpg",
    overview:
      "We design digital experiences that feel right. Clean layouts, thoughtful flows, and interfaces that just work—because good design starts with your users. Our UI/UX approach combines aesthetics with functionality to create intuitive, engaging digital products.",
    features: [
      "User research and personas",
      "Information architecture",
      "Wireframing and prototyping",
      "Visual design systems",
      "Interaction design",
      "Usability testing",
      "Responsive design",
      "Accessibility compliance",
    ],
    technologies: [
      { name: "Design Tools", items: ["Figma", "Adobe XD", "Sketch", "InVision"] },
      { name: "Prototyping", items: ["Framer", "Principle", "ProtoPie", "Axure"] },
      { name: "Research", items: ["User interviews", "A/B testing", "Heatmaps", "Analytics"] },
      { name: "Frameworks", items: ["Material Design", "Apple HIG", "Design systems"] },
    ],
    process: [
      { step: 1, title: "Discovery", description: "Understand users and business goals" },
      { step: 2, title: "Research", description: "Analyze user needs and behaviors" },
      { step: 3, title: "Information Architecture", description: "Structure content and flow" },
      { step: 4, title: "Wireframing", description: "Create low-fidelity layouts" },
      { step: 5, title: "Visual Design", description: "Develop the aesthetic language" },
      { step: 6, title: "Prototyping & Testing", description: "Validate with real users" },
    ],
    benefits: [
      "Increased user satisfaction and engagement",
      "Reduced development costs through early validation",
      "Higher conversion rates",
      "Lower support and training costs",
      "Stronger brand perception",
    ],
  },
  {
    id: 10,
    title: "Game Development",
    shortDescription: "Engaging interactive experiences across platforms",
    heroImage: "/images/services/game-dev.jpg",
    overview:
      "We turn game ideas into rich, playable experiences—built with care, creativity, and modern engines, for everything from mobile to immersive VR games. Our game development combines compelling gameplay, stunning visuals, and technical excellence.",
    features: [
      "2D and 3D game development",
      "Mobile game creation",
      "VR/AR game experiences",
      "Multiplayer functionality",
      "Game mechanics design",
      "Character and environment design",
      "Game monetization strategies",
      "Cross-platform deployment",
    ],
    technologies: [
      { name: "Engines", items: ["Unity", "Unreal Engine", "Godot", "Custom engines"] },
      { name: "Platforms", items: ["iOS", "Android", "PC", "Console", "WebGL"] },
      { name: "Art", items: ["2D/3D modeling", "Animation", "VFX", "UI design"] },
      { name: "Backend", items: ["Multiplayer servers", "Leaderboards", "Cloud saves"] },
    ],
    process: [
      { step: 1, title: "Concept", description: "Define game concept and core mechanics" },
      { step: 2, title: "Pre-production", description: "Create design documents and prototypes" },
      { step: 3, title: "Production", description: "Develop gameplay, assets, and systems" },
      { step: 4, title: "Testing", description: "Playtest and refine game experience" },
      { step: 5, title: "Polish", description: "Optimize performance and add final touches" },
      { step: 6, title: "Launch", description: "Release and post-launch support" },
    ],
    benefits: [
      "Engaging entertainment experiences",
      "Educational and training applications",
      "Brand awareness through gamification",
      "New revenue streams",
      "Community building around your product",
    ],
  },
  {
    id: 11,
    title: "Mobile App Development",
    shortDescription: "Native and cross-platform mobile solutions",
    heroImage: "/images/services/mobile-app.jpg",
    overview:
      "We build mobile apps that are fast, clean, and user-friendly. Whether for iOS or Android, we make apps that people love to use. Our mobile solutions combine intuitive interfaces with powerful functionality to deliver exceptional user experiences.",
    features: [
      "Native iOS development",
      "Native Android development",
      "Cross-platform solutions",
      "Progressive Web Apps",
      "Offline functionality",
      "Push notifications",
      "Location-based services",
      "Mobile payment integration",
    ],
    technologies: [
      { name: "Native", items: ["Swift", "SwiftUI", "Kotlin", "Jetpack Compose"] },
      { name: "Cross-Platform", items: ["React Native", "Flutter", "Xamarin"] },
      { name: "Backend", items: ["Firebase", "AWS Amplify", "Node.js", "GraphQL"] },
      { name: "Testing", items: ["XCTest", "Espresso", "Detox", "Appium"] },
    ],
    process: [
      { step: 1, title: "Requirements", description: "Define app features and user stories" },
      { step: 2, title: "UX/UI Design", description: "Create mobile-first user experience" },
      { step: 3, title: "Development", description: "Build frontend and backend components" },
      { step: 4, title: "Testing", description: "Ensure quality across devices" },
      { step: 5, title: "Deployment", description: "Submit to app stores" },
      { step: 6, title: "Maintenance", description: "Provide updates and support" },
    ],
    benefits: [
      "Enhanced customer engagement",
      "Brand strengthening through quality experiences",
      "New revenue channels",
      "Improved customer service",
      "Valuable user data and insights",
    ],
  },
  {
    id: 12,
    title: "Web Development (Full Stack)",
    shortDescription: "End-to-end web solutions from frontend to backend",
    heroImage: "/images/services/web-dev.jpg",
    overview:
      "We craft websites and apps that do it all—front to back. Modern, secure, responsive, and made to grow with your business. Our full-stack web development creates seamless digital experiences that perform across all devices and platforms.",
    features: [
      "Responsive website development",
      "Progressive Web Apps (PWAs)",
      "E-commerce solutions",
      "Content management systems",
      "API development and integration",
      "Database design and optimization",
      "Web application development",
      "Performance optimization",
    ],
    technologies: [
      { name: "Frontend", items: ["React", "Vue.js", "Angular", "Next.js", "Tailwind CSS"] },
      { name: "Backend", items: ["Node.js", "Python", "PHP", "Ruby on Rails", "Java"] },
      { name: "Databases", items: ["PostgreSQL", "MongoDB", "MySQL", "Redis"] },
      { name: "DevOps", items: ["Docker", "CI/CD", "AWS", "Vercel", "Netlify"] },
    ],
    process: [
      { step: 1, title: "Discovery", description: "Gather requirements and plan architecture" },
      { step: 2, title: "Design", description: "Create wireframes and visual designs" },
      { step: 3, title: "Development", description: "Build frontend and backend systems" },
      { step: 4, title: "Testing", description: "Ensure quality and performance" },
      { step: 5, title: "Deployment", description: "Launch to production environment" },
      { step: 6, title: "Support", description: "Provide maintenance and updates" },
    ],
    benefits: [
      "Professional online presence",
      "Seamless user experience across devices",
      "Scalable solutions that grow with your business",
      "Improved conversion rates",
      "Reduced maintenance costs",
    ],
  },
  {
    id: 13,
    title: "Robotic Process Automation",
    shortDescription: "Software robots that streamline business processes",
    heroImage: "/images/services/rpa.jpg",
    overview:
      "We build bots that handle your repetitive tasks—freeing up your team to focus on real work, not paperwork or copy-pasting. Our RPA solutions automate routine business processes to increase efficiency, reduce errors, and lower operational costs.",
    features: [
      "Process analysis and mapping",
      "Bot development and deployment",
      "Attended and unattended automation",
      "Integration with existing systems",
      "Cognitive automation with AI",
      "Process monitoring and analytics",
      "Exception handling",
      "Scalable automation frameworks",
    ],
    technologies: [
      { name: "Platforms", items: ["UiPath", "Automation Anywhere", "Blue Prism", "Microsoft Power Automate"] },
      { name: "AI Integration", items: ["OCR", "NLP", "Machine learning", "Computer vision"] },
      { name: "Integration", items: ["API", "Database", "Legacy systems", "ERP/CRM"] },
      { name: "Analytics", items: ["Process mining", "Performance dashboards", "ROI tracking"] },
    ],
    process: [
      { step: 1, title: "Process Assessment", description: "Identify automation candidates" },
      { step: 2, title: "Process Design", description: "Map and optimize workflows" },
      { step: 3, title: "Bot Development", description: "Build and configure automation" },
      { step: 4, title: "Testing", description: "Validate functionality and edge cases" },
      { step: 5, title: "Deployment", description: "Roll out to production environment" },
      { step: 6, title: "Monitoring", description: "Track performance and maintain bots" },
    ],
    benefits: [
      "Significant time savings on routine tasks",
      "Reduced error rates in processes",
      "24/7 operation capability",
      "Improved compliance and audit trails",
      "Quick ROI and cost reduction",
    ],
  },
  {
    id: 14,
    title: "Machine Learning Services",
    shortDescription: "Data-driven systems that learn and improve",
    heroImage: "/images/services/machine-learning.jpg",
    overview:
      "We create systems that learn from your data. From customer behavior to predictive insights, we help you work smarter every step of the way. Our machine learning solutions identify patterns, make predictions, and continuously improve with more data.",
    features: [
      "Supervised learning models",
      "Unsupervised learning",
      "Reinforcement learning",
      "Deep learning implementation",
      "Feature engineering",
      "Model training and validation",
      "MLOps and deployment",
      "Continuous model improvement",
    ],
    technologies: [
      { name: "Frameworks", items: ["TensorFlow", "PyTorch", "Scikit-learn", "XGBoost"] },
      { name: "Data Processing", items: ["Pandas", "NumPy", "Spark", "Dask"] },
      { name: "Cloud ML", items: ["AWS SageMaker", "Google Vertex AI", "Azure ML"] },
      { name: "Deployment", items: ["Docker", "Kubernetes", "Model serving", "API development"] },
    ],
    process: [
      { step: 1, title: "Problem Framing", description: "Define ML objectives and metrics" },
      { step: 2, title: "Data Preparation", description: "Collect, clean, and transform data" },
      { step: 3, title: "Feature Engineering", description: "Create relevant model inputs" },
      { step: 4, title: "Model Development", description: "Train and tune ML models" },
      { step: 5, title: "Evaluation", description: "Validate against business metrics" },
      { step: 6, title: "Deployment", description: "Integrate into production systems" },
    ],
    benefits: [
      "Accurate predictions for business planning",
      "Personalized customer experiences",
      "Automated decision-making",
      "Identification of hidden patterns",
      "Continuous improvement with new data",
    ],
  },
  {
    id: 15,
    title: "Natural Language Processing (NLP)",
    shortDescription: "AI systems that understand and generate human language",
    heroImage: "/images/services/nlp.jpg",
    overview:
      "We teach machines to understand and respond to human language—powering smarter chatbots, better search tools, and voice systems that actually get it. Our NLP solutions enable computers to comprehend, interpret, and generate human language in valuable ways.",
    features: [
      "Text classification and categorization",
      "Sentiment analysis",
      "Named entity recognition",
      "Language generation",
      "Summarization",
      "Question answering systems",
      "Multilingual support",
      "Voice recognition integration",
    ],
    technologies: [
      { name: "Models", items: ["BERT", "GPT", "T5", "RoBERTa", "Custom models"] },
      { name: "Libraries", items: ["Hugging Face", "spaCy", "NLTK", "Gensim"] },
      { name: "Cloud NLP", items: ["Google NLP", "AWS Comprehend", "Azure Text Analytics"] },
      { name: "Deployment", items: ["API services", "Edge deployment", "Embedded solutions"] },
    ],
    process: [
      { step: 1, title: "Use Case Definition", description: "Identify language processing needs" },
      { step: 2, title: "Data Collection", description: "Gather relevant text data" },
      { step: 3, title: "Model Selection", description: "Choose appropriate NLP approaches" },
      { step: 4, title: "Training", description: "Fine-tune models on domain data" },
      { step: 5, title: "Evaluation", description: "Test language understanding accuracy" },
      { step: 6, title: "Integration", description: "Deploy into applications" },
    ],
    benefits: [
      "Automated content analysis at scale",
      "Enhanced customer interactions",
      "Multilingual capabilities",
      "Efficient information extraction",
      "Improved search and discovery",
    ],
  },
  {
    id: 16,
    title: "Data Science Services",
    shortDescription: "Extracting insights and value from complex data",
    heroImage: "/images/services/data-science.jpg",
    overview:
      "We help businesses dig deep into their data, uncover patterns, predict outcomes, and make confident, data-driven decisions that drive results. Our data science approach combines statistical analysis, machine learning, and domain expertise to solve complex problems.",
    features: [
      "Exploratory data analysis",
      "Statistical modeling",
      "Predictive analytics",
      "Prescriptive analytics",
      "Time series forecasting",
      "A/B testing frameworks",
      "Anomaly detection",
      "Causal inference",
    ],
    technologies: [
      { name: "Languages", items: ["Python", "R", "SQL", "Julia"] },
      { name: "Libraries", items: ["Pandas", "NumPy", "SciPy", "Statsmodels"] },
      { name: "Visualization", items: ["Matplotlib", "Seaborn", "Plotly", "D3.js"] },
      { name: "Big Data", items: ["Spark", "Hadoop", "Databricks", "Snowflake"] },
    ],
    process: [
      { step: 1, title: "Problem Definition", description: "Clarify business questions" },
      { step: 2, title: "Data Collection", description: "Gather and integrate relevant data" },
      { step: 3, title: "Data Cleaning", description: "Prepare data for analysis" },
      { step: 4, title: "Exploration", description: "Discover patterns and relationships" },
      { step: 5, title: "Modeling", description: "Apply statistical and ML techniques" },
      { step: 6, title: "Interpretation", description: "Translate findings into business insights" },
    ],
    benefits: [
      "Evidence-based decision making",
      "Reduced uncertainty in planning",
      "Optimization of business processes",
      "Competitive intelligence",
      "Early identification of opportunities and risks",
    ],
  },
];
